version: '3.8'

services:
  # Servicio Web: Aplicación PHP + Apache con drivers SQL Server
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: planillacr_web
    restart: always
    ports:
      - "8085:80"
    environment:
      # Configuración de base de datos leída por config/conexion.php
      - DB_HOST="172.25.2.3,1443"
      - DB_NAME=PlanillaCR
      - DB_USER=sa
      - DB_PASS=Latin123
